name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.13.8'

dependencies:
  animate_do: ^3.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  go_router: ^11.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
